Layout
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #11
Opened 2021-05-26 20:34 UTC by aSosunoff

2021-05-26 20:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 21:24 UTC, GSemikozov requested changes

2021-05-26 21:24 UTC, GSemikozov commented on component-page.html
> +              <div class="menu__item">
этот и 2 последующих элементы - это один компонент, переключалка темы, пока добавлять не надо

2021-05-26 21:24 UTC, GSemikozov commented on components/component-menu/component-menu.css
> +  color: #000000;
можно использовать черный из переменных

2021-05-26 21:24 UTC, GSemikozov commented on components/component-menu/component-menu.css
> +  margin-bottom: 16px;
margin-bottom. уже определен чуть выше

2021-05-27 14:29 UTC, aSosunoff commented on component-page.html
> +              <div class="menu__item">
принял

2021-05-27 14:30 UTC, aSosunoff commented on components/component-menu/component-menu.css
> +  color: #000000;
принял

2021-05-27 14:31 UTC, aSosunoff commented on components/component-menu/component-menu.css
> +  margin-bottom: 16px;
принял

2021-05-28 16:16 UTC, GSemikozov approved these changes

2021-05-28 16:16 UTC, merged