added avatar
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #14
Opened 2021-05-29 06:32 UTC by aSosunoff

2021-05-29 06:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 10:25 UTC, GSemikozov requested changes

2021-05-30 10:25 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  width: var(--size, 102px);
в этом ПР-е не вижу, откуда тянутся эти переменные (видимо, предполагается что будут прокидываться инлайном?).

2021-05-30 10:25 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  width: var(--size, 102px);
тогда в любом случае стоит ограничить сайз тремы опциями (чтобы девелоперы не могли произвольные числа закидывать)

2021-05-30 21:54 UTC, aSosunoff commented on 06-lection4/01-avatar/avatar.css
> +  width: var(--size, 102px);
да инлайном если не достаточно модификаторов. Какими опциями ограничить не понял?

2021-06-01 10:38 UTC, GSemikozov requested changes

2021-06-01 10:38 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  width: var(--size, 102px);
переменные назвать --size-sm и тд.  И использовать в конкретном классе-модификаторе. Нам достаточно при необходимости менять значения лишь переменных, если надумаем в какой-то момент поменять значение _sm с 64 на 32 например. Но - твой вариант решения тоже имеет место быть, если хочешь оставить так - то ок, напиши в комменте ниже

2021-06-01 20:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 16:57 UTC, aSosunoff commented on 06-lection4/01-avatar/avatar.css
> +  width: var(--size, 102px);
принял

2021-06-03 13:06 UTC, GSemikozov approved these changes

2021-06-03 13:06 UTC, merged