fix
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #17
Opened 2021-05-29 10:45 UTC by aSosunoff

2021-05-29 10:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 08:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 10:28 UTC, GSemikozov requested changes

2021-05-30 10:28 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <use xlink:href="./svg-sprite.svg#frame_37"></use>
имя иконке лучше давать более смысловое и понятное

2021-05-30 10:28 UTC, GSemikozov commented on assets/svg-sprite.svg
> +        <symbol id="frame_37">
лучше задать более осмысленное имя иконке

2021-05-30 10:28 UTC, GSemikozov commented on assets/svg-sprite.svg
> +                fill="#212429" />
кроме того - можем использовать прием с currentColor

2021-05-30 10:28 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  fill: none;
лучше задать fill как  currentColor, и здесь не отменять заполнение fill, а задавать цвет через привычный нам `color`

2021-05-31 16:06 UTC, aSosunoff commented on 03-lection1/02-accordion/index.html
> +            <use xlink:href="./svg-sprite.svg#frame_37"></use>
принял

2021-05-31 16:06 UTC, aSosunoff commented on assets/svg-sprite.svg
> +        <symbol id="frame_37">
принял

2021-05-31 16:10 UTC, aSosunoff commented on 03-lection1/02-accordion/index.html
> +            <use xlink:href="./svg-sprite.svg#frame_37"></use>
принял

2021-05-31 16:11 UTC, aSosunoff commented on assets/svg-sprite.svg
> +                fill="#212429" />
принял

2021-05-31 16:11 UTC, aSosunoff commented on 03-lection1/02-accordion/accordion.css
> +  fill: none;
принял

2021-06-01 10:34 UTC, GSemikozov approved these changes

2021-06-01 10:34 UTC, merged