fix logo
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #18
Opened 2021-05-30 09:04 UTC by aSosunoff

2021-05-30 09:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-30 10:26 UTC, GSemikozov requested changes

2021-05-30 10:26 UTC, GSemikozov commented on components/logo/logo.svg
> +<?xml version="1.0" encoding="utf-8"?>
эту строку не обязательно копиировать

2021-05-31 16:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-31 16:02 UTC, aSosunoff commented on components/logo/logo.svg
> +<?xml version="1.0" encoding="utf-8"?>
принял

2021-05-31 16:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-31 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-31 17:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-31 19:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-01 10:33 UTC, GSemikozov approved these changes

2021-06-01 10:33 UTC, merged