added style for input
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #24
Opened 2021-06-03 16:37 UTC by aSosunoff

2021-06-03 16:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-04 14:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 15:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 15:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-04 19:44 UTC, GSemikozov requested changes

2021-06-04 19:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form-input__label-container {
здесь и ниже - многовато вышло контейнеров. С точки зрения формальностей - правила соблюдены.

но - в качестве рекомендации - я бы советовал немного скорректировать структуру блока по БЭМ.

во-первых, можно было бы разделить сложный компонент на два более простых - `.form-group` (у которого был бы `form-group__label` вместо `form-group__label-container`) и `.input` (`.input` вместо `.input-container`, `input__field` вместо `input-container__input`, `.input__icon` вместо `.input-container__input-icon`)

на мой взгляд так было бы более чисто и семантически грамотно.

но - это только рекомендация, переделывать не обязательно.

2021-06-05 10:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-06 12:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-06 12:06 UTC, aSosunoff commented on 07-lection5/04-input/input.css
> +.form-input__label-container {
принял

2021-06-06 12:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 11:51 UTC, GSemikozov approved these changes

2021-06-08 11:52 UTC, merged