Layout
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #25
Opened 2021-06-06 13:26 UTC by aSosunoff

added components to main box

2021-06-06 13:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-08 11:55 UTC, GSemikozov requested changes

2021-06-08 11:55 UTC, GSemikozov commented on components/footer/footer.css
> +  width: 640px;
лучше max-width - тогда при сужении экрана блок тоже будет сужаться и не будет создавать горизонтальный скрол

2021-06-08 20:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-08 20:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 20:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 21:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-10 17:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-11 18:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-11 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-12 12:39 UTC, aSosunoff commented on components/footer/footer.css
> +  width: 640px;
принял

2021-06-12 12:44 UTC, GSemikozov approved these changes

2021-06-12 12:44 UTC, merged