added burger menu
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #27
Opened 2021-06-18 15:15 UTC by aSosunoff

2021-06-18 15:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-18 19:24 UTC, GSemikozov requested changes

2021-06-18 19:24 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +              <div class="burger-menu-open__item"></div>
лучше все-таки забрать иконку из фигмы

2021-06-18 19:24 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +            <label class="dark-mode-toggler">
отдельная реализация под переключалку темы именно в бургер меню? 
желательно переиспользовать те компоненты которые уже есть - то есть обычный стилизованный ранее toggle инпут

2021-06-18 19:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-18 19:49 UTC, aSosunoff commented on 09-lection7/01-burger-menu/index.html
> +              <div class="burger-menu-open__item"></div>
принято

2021-06-18 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-18 20:11 UTC, aSosunoff commented on 09-lection7/01-burger-menu/index.html
> +            <label class="dark-mode-toggler">
принято

2021-06-18 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-21 08:50 UTC, GSemikozov approved these changes

2021-06-21 08:50 UTC, merged