Final
js-tasks-ru/htmlcss-20210513_al-sosunoff pull request #29
Opened 2021-07-02 20:01 UTC by aSosunoff

2021-07-02 20:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-03 11:57 UTC, GSemikozov requested changes

2021-07-03 11:57 UTC, GSemikozov commented on index.html
> +    <link rel="stylesheet" href="./components/sun/sun.css" />
все-таки решаем использовать как отдельные компоненты 2 отдельные иконки?)

2021-07-03 11:57 UTC, GSemikozov commented on index.html
> +              <div class="menu__item">
чтобы сделать все красиво, то иконки по краям - они все-таки составляют единое целое с toggler,  то есть это блок "переключатель темы", и логично их воспринимать как внутренние элементы toggler-а, а не отдельные элементы меню.

2021-07-04 07:36 UTC, aSosunoff commented on index.html
> +    <link rel="stylesheet" href="./components/sun/sun.css" />
Интересный вопрос

2021-07-04 07:37 UTC, aSosunoff commented on index.html
> +              <div class="menu__item">
Но разве это не частный случай. И нужен только 1 раз

2021-07-04 07:40 UTC, aSosunoff commented on index.html
> +              <div class="menu__item">
?

2021-07-18 11:34 UTC, aSosunoff commented on index.html
> +    <link rel="stylesheet" href="./components/sun/sun.css" />
Сделал отдельный компонент

2021-07-18 11:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-18 11:35 UTC, aSosunoff commented on index.html
> +              <div class="menu__item">
Сделал как отдельный компонент

2021-07-18 11:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 12:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 13:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 14:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 14:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 14:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 14:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 14:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-19 10:04 UTC, GSemikozov requested changes

2021-07-19 10:04 UTC, GSemikozov commented on components/toogler-change-theme/toogler-change-theme.css
> +.toggler-change-theme__sun {
не принципиально, но все же в плане улучшения здесь можно было бы задать более семантический класс, например .toggler-theme__light-theme-icon

2021-07-19 14:05 UTC, aSosunoff commented on components/toogler-change-theme/toogler-change-theme.css
> +.toggler-change-theme__sun {
принял

2021-07-19 14:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-24 09:20 UTC, GSemikozov requested changes

2021-07-24 09:20 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +html:not(.style-scope)[data-theme-dark] .calendar {
вот такие манипуляции мы не можем делать прямо внутри самого компонента, можно добавить там где в целом описывается темизация

2021-07-24 09:20 UTC, GSemikozov commented on components/header/header.css
> +.header__logo_component {
пустые классы удаляем

2021-07-24 09:20 UTC, GSemikozov commented on components/menu/menu.css
> +.menu_component {
пустые классы удаляем

2021-07-24 09:20 UTC, GSemikozov commented on components/toogler-change-theme/toogler-change-theme.css
> +.toggler-theme__light-theme-icon {
удалим)

2021-07-24 10:17 UTC, aSosunoff commented on components/header/header.css
> +.header__logo_component {
принял

2021-07-24 10:18 UTC, aSosunoff commented on components/menu/menu.css
> +.menu_component {
принял

2021-07-24 10:21 UTC, aSosunoff commented on components/toogler-change-theme/toogler-change-theme.css
> +.toggler-theme__light-theme-icon {
принял

2021-07-24 10:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-24 10:29 UTC, aSosunoff commented on 05-lection3/03-calendar/calendar.css
> +html:not(.style-scope)[data-theme-dark] .calendar {
Принял

2021-07-24 10:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-24 12:48 UTC, GSemikozov approved these changes

2021-07-24 12:48 UTC, merged